services:
  db_test:
    image: postgres:17.5
    container_name: test
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tests
    depends_on:
      db_test:
        condition: service_healthy
    volumes:
      - ./tests:/app/tests
      - ./fastapi_app:/app/fastapi_app

    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://test:test@db_test:5432/test_db
      APP_CONFIG__URL_TEST__URI: postgresql+asyncpg://test:test@db_test:5432/test_db

    command: >
      bash -c "
      pytest tests --disable-warnings --maxfail=3
      "
